version: '2'

services:
  nginx:
    build:
      context: ../
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ../build:/code/public
      - ../images:/code/public/images
      - ../videos:/code/public/videos
    ports:
      - '80:80'

  node:
    build:
      context: ../
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - ../:/code
