version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/avocado-tracker-nginx
    restart: on-failure
    environment:
      - VIRTUAL_HOST=avocado.wouterdeschuyter.be
      - LETSENCRYPT_HOST=avocado.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    volumes:
      - ./images:/code/public/images
    networks:
      - default
      - webproxy

networks:
  webproxy:
    external: true
